pull_request_rules:
    - name: Automatic merge on CI success and review
      conditions:
          - base=master
          - label=automerge
          - label!=do-not-merge
          - "#approved-reviews-by>=1"
          - "#changes-requested-reviews-by=0"
          - status-success=build (8.x)
          - status-success=build (10.x)
          - status-success=build (12.x)
          - status-success=deploy/netlify
      actions:
          merge:
              method: squash
    - name: Automatic merge for Dependabot pull requests
      conditions:
          - author=dependabot-preview[bot]
          - status-success=build (8.x)
          - status-success=build (10.x)
          - status-success=build (12.x)
          - status-success=deploy/netlify
      actions:
          merge:
              method: squash
