name: Node CI

on: [push]

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [8.x, 10.x, 12.x]

        steps:
            - uses: actions/checkout@v1
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node-version }}
            - name: Install Dependencies
              run: yarn
              env:
                  CI: true
            - name: Build Packages
              run: yarn run build
              env:
                  CI: true
            - name: Test Packages
              run: yarn run test
              env:
                  CI: true
